#!/bin/sh
#
# Update the current version date in DATESTAMP files and generate
# ChangeLog file entries since the last DATESTAMP update from the
# commit messages.

GITROOT=${GITROOT:-"/git/scpel_compiler.git"}
if [ -z "$TMPDIR" ]; then
  if [ -d /sourceware/snapshot-tmp/scpel_compiler ]; then
    TMPDIR=/sourceware/snapshot-tmp/scpel_compiler
  else
    TMPDIR=/tmp
  fi
fi

# Run this from $TMPDIR.
export GITROOT TMPDIR
BASEDIR=`mktemp -d`
cd "$BASEDIR"

GIT=${GIT:-/usr/local/bin/git}

# Assume all will go well.
SUBDIR="$BASEDIR/scpel_compiler"
${GIT} clone -q -b master "$GITROOT" "$SUBDIR"

cp -a "$SUBDIR"/contrib/scpel_compiler-changelog "$BASEDIR"/scpel_compiler-changelog
cd "$SUBDIR"
python3 ../scpel_compiler-changelog/git_update_version.py -p
RESULT=$?

cd "$TMPDIR"

/bin/rm -rf "$BASEDIR"
exit $RESULT
