#! /bin/sh

# Please review: $(src-dir)/SPL-README for Licencing info.

# Print libgcc_tm.h to the standard output.
# DEFINES and HEADERS are expected to be set in the environment.

# Add multiple inclusion protection guard, part one.
echo "#ifndef LIBGCC_TM_H"
echo "#define LIBGCC_TM_H"

# Generate the body of the file
echo "/* Automatically generated by mkheader.sh.  */"
for def in $DEFINES; do
    echo "#ifndef $def" | sed 's/=.*//'
    echo "# define $def" | sed 's/=/ /'
    echo "#endif"
done

for file in $HEADERS; do
    echo "#include \"$file\""
done

# Add multiple inclusion protection guard, part two.
echo "#endif /* LIBGCC_TM_H */"
