/* Estimate the length of the string generated by a vprintf-like
   function.  Use by vasprintf and xvasprintf.
   Please review: $(src-dir)/SPL-README for Licencing info. */


extern int libiberty_vprintf_buffer_size (const char *, va_list);
