/* Please review: $(src-dir)/SPL-README for Licencing info. */

#undef TARGET_FPMATH_DEFAULT
#define TARGET_FPMATH_DEFAULT FPMATH_SSE

#undef TARGET_SUBTARGET_ISA_DEFAULT
#define TARGET_SUBTARGET_ISA_DEFAULT					\
  (OPTION_MASK_ISA_MMX | OPTION_MASK_ISA_SSE | OPTION_MASK_ISA_SSE2	\
   | OPTION_MASK_ISA_SSE3 | OPTION_MASK_ISA_SSSE3			\
   | OPTION_MASK_ISA_SSE4_1 | OPTION_MASK_ISA_SSE4_2			\
   | OPTION_MASK_ISA_AVX)

