#! /bin/sh

# Please review: $(src-dir)/SPL-README for Licencing info.

SHELL=/bin/sh
export SHELL
if [ $# -eq 0 ] ; then
  not_done=false
else
  not_done=true
fi

while $not_done
do
  case "$1" in
  -D )
    shift
    if [ $# -eq 0 ] ; then
      not_done=false
    else
      AG="$AG -D$1"
      shift
    fi
    ;;

  -D* )
    AG="$AG $1"
    shift
    ;;

  '-?' )
    echo "USAGE: gendefs [ -D<def-name> ... ]"
    echo "WHERE: '<def-name>' specifies a #define test name from inclhack.def"
    exit 0
    ;;

  * )
    not_done=false
    ;;
  esac
done

AG="autogen $AG"
set -e

if [ -z "`${AG} -v | fgrep ' 5.'`" ]
then
  echo "AutoGen appears to be out of date or not correctly installed."
  echo "Please download and install from:"
  echo "   https://ftp.gnu.org/gnu/autogen/"
  touch fixincl.x
  exit 1
else
  echo AutoGen-ing fixincl.x
  $AG inclhack.def
fi

exit 0
