/* The C source file generated by flex includes stdio.h before any of
   the C code in itbl-lex.l.  Make sure we include as.h first, so
   that config.h can set the correct values for various things.  */

#include "as.h"
#include "itbl-lex.c"
